-- Live Fee Auto-Sync — pg_cron scheduling
--
-- Ini BUKAN migration otomatis seperti file lain di folder ini. Isinya sengaja
-- di-comment out karena butuh 2 nilai yang cuma diketahui pas deploy:
--   1. URL production project ini (mis. https://xxxx.vercel.app)
--   2. Isi env LIVE_FEE_SYNC_SECRET yang sama persis dengan yang di-set di server
--
-- Cara aktivasi (jalankan manual di Supabase SQL Editor, BUKAN lewat migration
-- runner otomatis):
--   1. Buka Supabase Dashboard -> Database -> Extensions -> aktifkan
--      "pg_cron" dan "pg_net" kalau belum aktif (kemungkinan sudah aktif dari
--      setup cron lain).
--   2. Copy blok SQL di bawah, ganti dua placeholder:
--        <PRODUCTION_URL>        -> domain production (tanpa trailing slash)
--        <LIVE_FEE_SYNC_SECRET>  -> isi env LIVE_FEE_SYNC_SECRET
--   3. Pastikan DASH_MGMT_API_TOKEN sudah di-set di server (Vercel) SEBELUM
--      cron ini jalan, kalau tidak endpoint akan error tiap kali dipanggil.
--   4. Jalankan di SQL Editor. Sekali jalan, cron langsung terjadwal —
--      tidak perlu diulang tiap deploy.
--   5. Cek jadwal aktif: SELECT * FROM cron.job;
--   6. Cek histori run & response: SELECT * FROM cron.job_run_details
--      ORDER BY start_time DESC LIMIT 10;
--
-- Jadwal di bawah: 2x sehari, jam 09:50 & 17:50 UTC (16:50 & 00:50 WIB) —
-- SENGAJA 10 menit SEBELUM cron 'payroll-workflow-daily' (10:00 & 18:00 UTC,
-- lihat 20260720000001_payroll_workflow_cron.sql), biar data delivery/
-- attendance yang di-sync live sudah pasti masuk duluan sebelum
-- payroll-workflow generate/regenerate payroll run dari data itu.
-- Format cron: menit jam tanggal bulan hari-minggu (semua dalam UTC).

-- create extension if not exists pg_cron;
-- create extension if not exists pg_net;
--
-- select cron.schedule(
--   'live-fee-sync-twice-daily',
--   '50 9,17 * * *', -- tiap hari jam 09:50 & 17:50 UTC (16:50 & 00:50 WIB)
--   $$
--   select net.http_post(
--     url := '<PRODUCTION_URL>/api/live-fee-sync',
--     headers := jsonb_build_object(
--       'Content-Type', 'application/json',
--       'x-live-fee-sync-secret', '<LIVE_FEE_SYNC_SECRET>'
--     ),
--     body := '{}'::jsonb
--   );
--   $$
-- );

-- Untuk ganti jadwal atau matikan cron:
--   select cron.unschedule('live-fee-sync-twice-daily');
--   -- lalu jalankan ulang cron.schedule(...) di atas dengan jadwal baru.

-- Untuk backfill/test manual periode tertentu:
--   curl -X POST https://dash-payroll-engine.vercel.app/api/live-fee-sync \
--     -H "Content-Type: application/json" \
--     -H "x-live-fee-sync-secret: <secret>" \
--     -d '{"from": "2026-07-20", "to": "2026-07-21"}'
