-- Payroll Workflow — pg_cron scheduling
--
-- SUPERSEDED (2026-08-17): 'payroll-workflow-h1' & 'payroll-workflow-same-day'
-- sudah di-unschedule dari production. Diganti 4 checkpoint seragam (01:00,
-- 06:00, 10:00, 16:00 WIB), tiap checkpoint cek SEMUA client due tanpa
-- closeSameDayFilter — lihat 20260817000000_unified_checkpoint_cron.sql.
-- File ini dibiarkan sebagai riwayat/referensi cara kerja resolvePeriodIfDue
-- & findOrCreatePayrollRun di bawah, JANGAN jalanin ulang block cron.schedule
-- di sini — SELALU cek `select * from cron.job;` langsung ke production
-- buat jadwal yang beneran aktif.
--
-- Jadwal aktif: SETIAP HARI, 2 cron TERPISAH berdasarkan tipe tutup buku:
--
--   1. Jam 09:00 WIB (02:00 UTC, dipercepat dari 12:00 -> 09:00 pada 2026-08-17)
--      — hitung payroll client TUTUP H-1 (close_same_day = false). Data udah
--      ditarik dari sync jam 06:00 WIB (buffer 3 jam sebelum job jalan).
--
--   2. Jam 16:00 WIB (09:00 UTC, dipercepat dari 17:00 -> 16:00 pada 2026-08-13)
--      — hitung payroll client TUTUP HARI SAMA (close_same_day = true, termasuk
--      Otts and Jill). Data baru di-sync jam 15:50 WIB.
--
-- Urutan harian (lihat juga 20260730000001_live_fee_sync_cron.sql):
--   06:00 WIB  live-fee-sync (tarik data KEMARIN)
--   09:00 WIB  payroll-workflow H-1
--   15:50 WIB  live-fee-sync (tarik data HARI INI)
--   16:00 WIB  payroll-workflow same-day
--
-- PENTING: tombol manual "Run Workflow Sekarang" (triggerPayrollWorkflow di
-- payroll-workflow.functions.ts) TIDAK mengirim closeSameDayFilter — jadi dia
-- memproses SEMUA periode yang jatuh tempo hari itu, TANPA peduli jam berapa
-- sekarang atau apa datanya udah lengkap (lihat insiden Otts and Jill,
-- 2026-08-13: diklik jam 12:54 & 14:30 WIB, prematur karena data hari itu
-- belum ke-sync). Ini bukan bug — tombol itu emang buat override manual/testing
-- — tapi jangan diklik buat client close_same_day=true sebelum jam tutup datanya.

-- create extension if not exists pg_cron;
-- create extension if not exists pg_net;
--
-- -- Cron 1: Jam 09:00 WIB — client tutup H-1
-- select cron.schedule(
--   'payroll-workflow-h1',
--   '0 2 * * *', -- tiap hari jam 02:00 UTC (09:00 WIB)
--   $$
--   select net.http_post(
--     url := '<PRODUCTION_URL>/api/payroll-workflow',
--     headers := jsonb_build_object(
--       'Content-Type', 'application/json',
--       'x-payroll-workflow-secret', '<PAYROLL_WORKFLOW_SECRET>'
--     ),
--     body := '{"trigger": "scheduler", "closeSameDayFilter": "h-1"}'::jsonb
--   );
--   $$
-- );
--
-- -- Cron 2: Jam 16:00 WIB — client tutup hari sama
-- select cron.schedule(
--   'payroll-workflow-same-day',
--   '0 9 * * *', -- tiap hari jam 09:00 UTC (16:00 WIB)
--   $$
--   select net.http_post(
--     url := '<PRODUCTION_URL>/api/payroll-workflow',
--     headers := jsonb_build_object(
--       'Content-Type', 'application/json',
--       'x-payroll-workflow-secret', '<PAYROLL_WORKFLOW_SECRET>'
--     ),
--     body := '{"trigger": "scheduler", "closeSameDayFilter": "same-day"}'::jsonb
--   );
--   $$
-- );

-- Untuk ganti jadwal atau matikan cron:
--   select cron.unschedule('payroll-workflow-h1');
--   select cron.unschedule('payroll-workflow-same-day');
