-- Live Fee Auto-Sync — pg_cron scheduling
--
-- SUPERSEDED (2026-08-17): 'live-fee-sync-h1-morning' & 'live-fee-sync-h0-close'
-- sudah di-unschedule dari production. Diganti sync di 4 checkpoint seragam
-- (01:00, 06:00, 10:00, 16:00 WIB) — lihat 20260817000000_unified_checkpoint_cron.sql.
-- File ini dibiarkan sebagai riwayat, JANGAN jalanin ulang block cron.schedule
-- di sini — SELALU cek `select * from cron.job;` langsung ke production buat
-- jadwal yang beneran aktif.
--
-- Jadwal aktif: 2 job terpisah, TIAP JOB kirim {from,to} EKSPLISIT untuk SATU
-- hari kalender (bukan window rolling 2 hari default) — supaya fee tiap hari
-- cuma dihitung ULANG persis 2x sepanjang hidupnya: sekali sebagai "H-1"
-- (kemarin, jam 06:00 WIB — udah pasti final, gak perlu buru-buru) dan sekali
-- sebagai "H-0" (hari ini, jam 15:50 WIB — 10 menit sebelum payroll-workflow
-- same-day jam 16:00 WIB baca datanya, lihat 20260720000001_payroll_workflow_cron.sql).
--   - live-fee-sync-h1-morning: 23:00 UTC = 06:00 WIB (hari berikutnya) -> tarik KEMARIN
--   - live-fee-sync-h0-close:   08:50 UTC = 15:50 WIB                  -> tarik HARI INI
-- Format cron: menit jam tanggal bulan hari-minggu (semua dalam UTC).
--
-- Cara ganti jadwal (jalankan di Supabase SQL Editor):
--   select cron.unschedule('live-fee-sync-h1-morning');
--   select cron.unschedule('live-fee-sync-h0-close');
--   -- lalu jalankan ulang 2 blok cron.schedule(...) di bawah dengan jadwal baru
--   -- (uncomment dulu, isi <PRODUCTION_URL>/<LIVE_FEE_SYNC_SECRET> yang asli).

-- create extension if not exists pg_cron;
-- create extension if not exists pg_net;
--
-- select cron.schedule(
--   'live-fee-sync-h1-morning',
--   '0 23 * * *', -- tiap hari jam 23:00 UTC (06:00 WIB besoknya) -> tarik KEMARIN
--   $$
--   select net.http_post(
--     url := '<PRODUCTION_URL>/api/live-fee-sync',
--     headers := jsonb_build_object(
--       'Content-Type', 'application/json',
--       'x-live-fee-sync-secret', '<LIVE_FEE_SYNC_SECRET>'
--     ),
--     body := jsonb_build_object(
--       'from', ((now() at time zone 'Asia/Jakarta')::date - 1)::text,
--       'to', ((now() at time zone 'Asia/Jakarta')::date - 1)::text
--     )
--   );
--   $$
-- );
--
-- select cron.schedule(
--   'live-fee-sync-h0-close',
--   '50 8 * * *', -- tiap hari jam 08:50 UTC (15:50 WIB) -> tarik HARI INI
--   $$
--   select net.http_post(
--     url := '<PRODUCTION_URL>/api/live-fee-sync',
--     headers := jsonb_build_object(
--       'Content-Type', 'application/json',
--       'x-live-fee-sync-secret', '<LIVE_FEE_SYNC_SECRET>'
--     ),
--     body := jsonb_build_object(
--       'from', ((now() at time zone 'Asia/Jakarta')::date)::text,
--       'to', ((now() at time zone 'Asia/Jakarta')::date)::text
--     )
--   );
--   $$
-- );

-- Untuk backfill/test manual periode tertentu:
--   curl -X POST https://dash-payroll-engine.vercel.app/api/live-fee-sync \
--     -H "Content-Type: application/json" \
--     -H "x-live-fee-sync-secret: <secret>" \
--     -d '{"from": "2026-07-20", "to": "2026-07-21"}'
